Nvcustomname_backend
green-fox-academy/huli-kalendaryo-backend pull request #116
Opened 2018-05-09 13:37 UTC by norvarju

2018-05-09 14:23 UTC, bekobarna reviewed
Because you no longer use the Faker library,  you can delete the dependency and the imported library line in the KalendarService class

2018-05-10 07:50 UTC, arnikaeva requested changes
Unit tests are missing, custom name should be optional.

2018-05-10 07:50 UTC, arnikaeva commented on build.gradle
> -	testCompile group: 'com.github.javafaker', name: 'javafaker', version: '0.12'
acceptance criteria: if no name is provided a default name will be used (existing solution)

2018-05-10 07:50 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/KalendarService.java
> +        kalendar.setName(kalendarFromAndroid.getCustomName());
if no name is provided, a fake name should be used

2018-05-10 07:50 UTC, arnikaeva commented on build.gradle
> -	testCompile group: 'com.github.javafaker', name: 'javafaker', version: '0.12'
unit tests are missing, check [Jira](http://jira.greenfox.academy/browse/OPAL-205) definition of done for details.

2018-05-16 13:39 UTC, closed without merging