OPAL-187 Readme update
green-fox-academy/huli-kalendaryo-backend pull request #117
Opened 2018-05-10 10:25 UTC by bekobarna

2018-05-14 12:28 UTC, Isshae submitted a review, later dismissed

2018-05-16 08:13 UTC, arnikaeva requested changes
Just minor changes needed

2018-05-16 08:13 UTC, arnikaeva commented on README.md
> +2. Ask us for the `debug.keystore` file (temporary method during development), which you need to put in your Users/"yourusername"/.android folder (in case of windows)
temporary method -> do you mean temporary solution?

2018-05-16 08:13 UTC, arnikaeva commented on README.md
> +3. Use "dev" as an @ActiveProfiles annotation in the main class (import the library, if necessary)
this should not be a separate step, but should be added to the code in dev branch

2018-05-17 07:50 UTC, arnikaeva approved these changes

2018-05-17 11:15 UTC, markaron approved these changes

2018-05-17 11:16 UTC, merged