Opal-207 backend can process account removal
green-fox-academy/huli-kalendaryo-backend pull request #123
Opened 2018-05-18 15:33 UTC by sznemeth3

2018-05-22 09:43 UTC, markaron submitted a review, later dismissed

2018-05-22 10:54 UTC, pataricza1987 submitted a review, later dismissed

2018-05-24 12:44 UTC, arnikaeva requested changes

2018-05-24 12:44 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/controllers/AuthController.java
> +      return ResponseEntity.status(200).body(authAndUserService.createPostAuthResponse(clientToken, googleAuth));
you can use 2 lines, so the `authAndUserService.createPostAuthResponse(clientToken, googleAuth)` call is not inside the body()

2018-05-24 12:44 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/AuthAndUserService.java
> +      throw new ValidationException("Client token/email is missing or invalid");
would be nice to know the exact error :)

2018-05-24 12:44 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/AuthAndUserService.java
> +  public KalUser setKalUserForPostAuth(String clientToken, GoogleAuth googleAuth) {
would refactor this method so it is evident what happens and why in the various cases

2018-05-24 12:44 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/AuthAndUserService.java
> +  public KalUser setKalUserForPostAuth(String clientToken, GoogleAuth googleAuth) {
something like
```
if (clientExists(clientToken) {
..
} else if (someOtherCheckerMethod()) { //not sure what happens here
...
} else {
  kalUser =  createNewUser();
}
```

2018-05-24 12:44 UTC, arnikaeva commented on src/test/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/AuthAndUserServiceTest.java
> +    GoogleAuth googleAuth = new GoogleAuth(email, authCode, displayName, kalUser, accesToken);
if you do not use the variables later on (in an assert) than there is no need to declare them, can use here  `GoogleAuth googleAuth = new GoogleAuth("email", "etc", ....);`

2018-05-24 12:44 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/AuthAndUserService.java
> +    return googleAuthRepository.findByEmailAndUser_Id(googleAuth.getEmail(), kalUserId) != null;
will this really be null? Or will this throw a nullPointerException?

2018-05-25 10:14 UTC, arnikaeva submitted a review, later dismissed

2018-05-25 10:59 UTC, pataricza1987 approved these changes

2018-05-25 12:14 UTC, markaron commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/controllers/AccountController.java
> +      authAndUserService.deleteGoogleAuth(email, clientToken);
Nice!

2018-05-25 12:15 UTC, markaron approved these changes

2018-05-25 12:17 UTC, merged