Opal 230 refactor kalendar controller
green-fox-academy/huli-kalendaryo-backend pull request #130
Opened 2018-05-28 10:12 UTC by pataricza

2018-05-28 10:17 UTC, sznemeth3 submitted a review, later dismissed

2018-05-28 10:38 UTC, arnikaeva requested changes
Refactoring :)

2018-05-28 10:38 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/controllers/KalendarController.java
> +            KalendarListResponse kalendarListResponse = kalendarService.makeKalendarListResponse(clientToken);
I was thinking about renaming this method to be more descriptive - so when you check the KalendarService class it is meaningful and you do not need to check this calles method to understand what is happening.
Maybe `kalendarService.getKalendarsByUser` or `kalendarService.getKalendarsByClientToken` ?

2018-05-28 10:38 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/KalendarService.java
> +        for (int i = 0; i < kalendars.size(); i++) {
use streaming+ builder pattern for creating kalendarResponse

2018-05-28 10:38 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/KalendarService.java
> +            kalendarResponse.setInputGoogleCalendars((setToStringGoogleCalendars(findGoogleCalendarsByKalendar(kalendars.get(i)))));
nested method calls are hard to maintain and debug

2018-05-28 10:38 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/KalendarService.java
> +    private static final String USER_NOT_FOUND_TOKEN = "User not found for clientToken=";
I would not put exception messages as constants if we are not reusing them anywhere else

2018-05-28 10:38 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/opal/kalendaryo/kalendaryo/service/KalendarService.java
> +        for (int i = 0; i < kalendars.size(); i++) {
```java
List<Kalendar> kalendars = findKalendars(clientToken);
List<KalendarResponse> kalendarResponses = kalendars.stream
  .map(kalendar -> {
    new KalendarResponseBuilder
      .setOutputGoogleAuthId(kalendar.getOutputGoogleAuthId())
      .setId(..)
      ....
      .build();
   })
   .collectors(Collector.toList());
```

2018-05-28 16:06 UTC, closed without merging

2018-05-29 07:43 UTC, arnikaeva commented on src/main/java/com/greenfoxacademy/kalendaryo/model/builder/KalendarResponseBuilder.java
> +    return  new KalendarResponse(outputGoogleAuthId, outputCalendarId, inputGoogleCalendars, id);
unneccesary space after `return` 😄 
btw great work you could do a small lightning talk about the builder pattern sometime :)